Fix Test output

diff --git a/.ci/Makefile b/.ci/Makefile
--- a/.ci/Makefile
+++ b/.ci/Makefile
@@ -18,11 +18,22 @@ pull-latest:
 	docker pull $(REPOURL)/misp-dockerized-robot:latest-dev;
 	docker pull $(REPOURL)/misp-dockerized-misp-modules:latest-dev;
 
+# https://stackoverflow.com/questions/13068152/grep-exit-codes-in-makefile#13069387
 test:
 	@echo "################		Start Tests		###########################"
-	-docker exec misp-robot bash -c "/srv/scripts/test.sh"
-	@if [ ! -d reports ]; then mkdir reports; fi
-	@docker cp misp-robot:/srv/MISP-dockerized-testbench/reports/. reports/
+	@if [ ! -d reports ]; then mkdir reports; fi ;\
+	docker exec misp-robot bash -c "sleep 10 && /srv/scripts/test.sh" 2> reports/error.txt \
+	retVal=$$? ;\
+	docker cp misp-robot:/srv/MISP-dockerized-testbench/reports/. reports/ ;\
+	if $$retval; then echo ""; \
+		echo "[ERROR] Test was not successful. Output Logs from Container and exit."; echo ""; \
+		echo "error output:"; cat reports/error.txt; echo ""; \
+		echo "misp-proxy:"; docker logs misp-proxy --tail 20; echo ""; \
+		echo "misp-server:"; docker logs misp-server --tail 20; echo "";  \
+		echo "misp-modules:" ; docker logs misp-modules --tail 20; echo ""; \
+		echo "[ERROR] Test was not successful."; echo ""; \
+		exit 1 ;\
+	else "[Info] Test was successful" && echo ""  && exit 0; fi
 
 tag:
 	@bash 20_tag_2_registry.sh $(REPOURL) $(USER) $(PW)
